### ISSUE TITLE
Lambda ImportVulToSecurityHub

### ISSUE THREAD

**Issue by jsebastiancortes** [aws-samples/devsecops-cicd#5]
Hi , any help with this error .  
![LAMBDA](https://user-images.githubusercontent.com/93729257/149628243-f6a3e5e6-a9df-4b3f-a247-671bc0bf99a2.png)
[import_findings_security_hub.zip](https://github.com/aws-samples/devsecops-cicd/files/7875296/import_findings_security_hub.zip)

[ERROR] KeyError: 'messageType'
Traceback (most recent call last):
  File "/var/task/import_findings_security_hub.py", line 141, in lambda_handler
    return process_message(event)
  File "/var/task/import_findings_security_hub.py", line 27, in process_message
    if event['messageType'] == 'CodeScanReport':

**Comment by MoisesTapia** [comment]
@jsebastiancortes you can see my last open pull request with various updates, it is possible the answer to your problem you can be found it
